### ISSUE TITLE
maze generator tool

### ISSUE THREAD

**Issue by karry3775** [karry3775/Motley#5]
## Overview
This tool will be responsible for generating a maze as requested by user 
- If the user provides values for maze size and granularity, it should accept those values, otherwise just stick with the defaults
- It should also support various algorithms that the user can specify for maze generation
  - Randomized depth first search
  - Kruskal's algorithm
  - Prims algorithm etc.
- Should also support later in the future access for different shapes, and not just a square grid
- Ultimate aim for this tool is to be used as a visualizer and path planning aid to practice different path planning algorithms in grid based environments
- Later we can perhaps create another tool that can handle other environments other than maze

## TODO
- [x] Fix the logic for wall destruction
- [x] Fix the randomized depth first search 
- [x] Write a jank visualizer
- [x] Write a better visualizer that can handle progression of maze generation
- [ ] Add support for other algorithms like Kruskal's and Prim's
- [ ] Port to boost for sleep operations 
- [ ] Add glogging

## Current issues:
- ~~Randomized depth first search is not breaking enough walls, need to fix the logic there~~

## Linked directory
https://github.com/karry3775/Motley/tree/master/SDL_exploration/src
