### ISSUE TITLE
Path finding tool

### ISSUE THREAD

**Issue by karry3775** [karry3775/Motley#6]
## Overview
This tool will implement pathfinding tool which can support different environments i.e.
- [x] Maze -- (similar to https://github.com/karry3775/Motley/issues/5 but better )
- [x] Grid 
- [ ] Add more ...

and support path finding using  algorithms (as mentioned [here](https://en.wikipedia.org/wiki/Pathfinding#Hierarchical_path_finding)):

- [x]  [Dijkstra's](https://en.wikipedia.org/wiki/Pathfinding#Dijkstra's_algorithm)
- [ ]  [A*](https://en.wikipedia.org/wiki/Pathfinding#A*_algorithm)
- [ ]  [Sample Algorithm](https://en.wikipedia.org/wiki/Pathfinding#Sample_algorithm) 
- [ ]  [Hierarchical path finding](https://en.wikipedia.org/wiki/Pathfinding#Hierarchical_path_finding) 
- [ ]  [D*](https://en.wikipedia.org/wiki/D*) 
- [ ]  [Any angle path planning](https://en.wikipedia.org/wiki/Any-angle_path_planning) 
- [x]  BFS

## Current code is maintained at
- https://github.com/karry3775/Motley/tree/master/PathFinding

## TODO:

- [x]  Add support for maze
- [x] Add support for obstacles in grid
- [ ] Add support in environment generation so that other contributors can add new environments with ease
- [ ] Implement rest of the pathfinding algos (Currently single source minimum path using BFS)
- [ ] Implement rest of the algos for maze generation (Currently Randomized depth first search)
- [ ] Add message rendering when no path found!
- [ ] Investigate the possibility of adding dynamically moving obstacles in both grid and maze ( Could open up doors for long life A star or something) see (https://math.stackexchange.com/questions/2298507/maze-with-a-randomly-moving-obstacle)
